Testing all the possible GETs the app will have to get
tanadendere/whimsical-manga-reader pull request #2
Opened 2024-03-19 06:39 UTC by tanadendere

This PR introduces the api fetches and the interfaces that were created to create types from the API responses.

2024-03-19 10:12 UTC, yanevdw commented on src/models/chapter.d.ts
> +}
For these ```unknown``` values, if they are optional, you could do ```vol?: string``` for example where the string refers to the type of the parameter if it is not null.

2024-03-19 10:13 UTC, yanevdw commented on src/models/chapter.d.ts
> +  vol: unknown;
```Line 116```: Same here

2024-03-19 10:13 UTC, yanevdw commented on src/models/comicChapters.d.ts
> +  vol: unknown;
Same here.

2024-03-19 10:13 UTC, yanevdw commented on src/models/comicChapters.d.ts
> +  md_chapters_groups: MdChaptersGroup[];
Here as well.

2024-03-19 10:14 UTC, yanevdw commented on src/models/comicInfo.d.ts
> +  englishLink: unknown;
Here as well.

2024-03-19 10:15 UTC, yanevdw commented on src/models/comicInfo.d.ts
> +  vol: unknown;
Same here.

2024-03-19 10:15 UTC, yanevdw commented on src/models/comicInfo.d.ts
> +  demographic: unknown;
Here too.

2024-03-19 10:15 UTC, yanevdw commented on src/models/comicInfo.d.ts
> +  final_volume: unknown;
Here too.

2024-03-19 10:18 UTC, yanevdw requested changes
Well done! Just check all the unknowns in you models, if they are optional, rather define them as optional.

2024-03-19 17:32 UTC, yanevdw approved these changes
Changes have been implemented. Nicely done!

2024-03-20 04:00 UTC, LesediMoko reviewed
It all looks good. Just made a few comments regarding to the redundancy of your types as well as having a return type for your GET functions

2024-03-20 04:00 UTC, LesediMoko commented on src/models/chapter.d.ts
> +export interface Chapter2 {
Consider using the same type for Next and Chapter2. They have plenty of properties in common and those that are missing in one or the other can just be optional

2024-03-20 04:00 UTC, LesediMoko commented on src/models/searchResult.d.ts
> +export interface MdCover {
this is the second MDCover interface I've come across and they both have the same properties. Maybe just keep one and export when needed

2024-03-20 04:00 UTC, LesediMoko commented on src/models/topComic.d.ts
> +export interface ExtendedNew {
News and ExtendedNews have the same properties. Consider only keeping one

2024-03-20 04:00 UTC, LesediMoko commented on src/utilities/api.ts
consider adding a return type to your functions so that typescript doesn't infer them as 'any'.

2024-03-26 10:50 UTC, LesediMoko requested changes
Great job shaking off the repetitive interface, the code looks really good now! All that's missing are the return types in api.ts for your fetch responses and you'll be good to go 🏄🏽‍♂️

i.e. ` export function getComicInfo(slug: string) : Promise<IComicData> {...} ` 
or just ` export function getComicInfo(slug: string) : IComicData {...} ` if the promise is resolved within the function

2024-03-26 11:05 UTC, tanadendere commented
Thanks Lesedi, i had planned to add the add the return types in the next PR because I plan on implementing the API calls a bit differently.

2024-03-26 11:07 UTC, LesediMoko approved these changes
All my concerns have been addressed. Great work, Tana!

2024-03-26 11:34 UTC, merged